[data]
data_folder="C:/Users/Public/py_dev/fastapi/test_SQLModel/src/data"
[request_Server]
url="http://localhost:800/lisStock/"
# To Do .......
[PostgreSQL_DB]
host="localhost"
user="dev_user"
passwd="dev_password"
db_name="dev"
port=5433
pool_size = 2
max_overflow = 3
echo=true
